name: DCO
on:
  pull_request: {}
  workflow_dispatch: {}
  merge_group:
    types:
      - checks_requested
jobs:
  check-dco:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - name: Set up Python 3.x
        uses: actions/setup-python@0b93645e9fea7318ecaed2b359559ac225c90a2b # v5.3.0
        with:
          python-version: '3.x'
      - name: Check DCO
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pip3 install -U dco-check
          dco-check --exclude-pattern 'dependabot\[bot\]@users\.noreply\.github\.com'
